// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"net/http"
)

type AddUsedByReferenceRequest struct {
	// The unique identifier of the validation rule to update.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
	// The used_by reference to add
	UsedBy *shared.UsedBy `request:"mediaType=application/json"`
}

func (a *AddUsedByReferenceRequest) GetRuleID() string {
	if a == nil {
		return ""
	}
	return a.RuleID
}

func (a *AddUsedByReferenceRequest) GetUsedBy() *shared.UsedBy {
	if a == nil {
		return nil
	}
	return a.UsedBy
}

// AddUsedByReferenceValidationRulesResponseResponseBody - Internal Server Error
type AddUsedByReferenceValidationRulesResponseResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (a *AddUsedByReferenceValidationRulesResponseResponseBody) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

// AddUsedByReferenceValidationRulesResponseBody - Validation rule not found
type AddUsedByReferenceValidationRulesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (a *AddUsedByReferenceValidationRulesResponseBody) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

// AddUsedByReferenceResponseBody - Bad Request - Invalid request body
type AddUsedByReferenceResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (a *AddUsedByReferenceResponseBody) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

type AddUsedByReferenceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ValidationRule *shared.ValidationRule
	// Bad Request - Invalid request body
	FourHundredApplicationJSONObject *AddUsedByReferenceResponseBody
	// Validation rule not found
	FourHundredAndFourApplicationJSONObject *AddUsedByReferenceValidationRulesResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *AddUsedByReferenceValidationRulesResponseResponseBody
}

func (a *AddUsedByReferenceResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AddUsedByReferenceResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AddUsedByReferenceResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AddUsedByReferenceResponse) GetValidationRule() *shared.ValidationRule {
	if a == nil {
		return nil
	}
	return a.ValidationRule
}

func (a *AddUsedByReferenceResponse) GetFourHundredApplicationJSONObject() *AddUsedByReferenceResponseBody {
	if a == nil {
		return nil
	}
	return a.FourHundredApplicationJSONObject
}

func (a *AddUsedByReferenceResponse) GetFourHundredAndFourApplicationJSONObject() *AddUsedByReferenceValidationRulesResponseBody {
	if a == nil {
		return nil
	}
	return a.FourHundredAndFourApplicationJSONObject
}

func (a *AddUsedByReferenceResponse) GetFiveHundredApplicationJSONObject() *AddUsedByReferenceValidationRulesResponseResponseBody {
	if a == nil {
		return nil
	}
	return a.FiveHundredApplicationJSONObject
}
