// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"net/http"
)

type CreateValidationRuleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ValidationRule *shared.ValidationRule
}

func (c *CreateValidationRuleResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateValidationRuleResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateValidationRuleResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateValidationRuleResponse) GetValidationRule() *shared.ValidationRule {
	if c == nil {
		return nil
	}
	return c.ValidationRule
}
