// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteValidationRuleRequest struct {
	// The unique identifier of the validation rule to delete.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

func (o *DeleteValidationRuleRequest) GetRuleID() string {
	if o == nil {
		return ""
	}
	return o.RuleID
}

// DeleteValidationRuleResponseBody - Internal Server Error
type DeleteValidationRuleResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *DeleteValidationRuleResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type DeleteValidationRuleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Internal Server Error
	Object *DeleteValidationRuleResponseBody
}

func (o *DeleteValidationRuleResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteValidationRuleResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteValidationRuleResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteValidationRuleResponse) GetObject() *DeleteValidationRuleResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
