// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"net/http"
)

type GetValidationRuleByIDRequest struct {
	// The unique identifier of the validation rule to retrieve.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

func (o *GetValidationRuleByIDRequest) GetRuleID() string {
	if o == nil {
		return ""
	}
	return o.RuleID
}

// GetValidationRuleByIDValidationRulesResponseBody - Internal Server Error
type GetValidationRuleByIDValidationRulesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetValidationRuleByIDValidationRulesResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// GetValidationRuleByIDResponseBody - Validation rule not found
type GetValidationRuleByIDResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetValidationRuleByIDResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type GetValidationRuleByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ValidationRule *shared.ValidationRule
	// Validation rule not found
	FourHundredAndFourApplicationJSONObject *GetValidationRuleByIDResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetValidationRuleByIDValidationRulesResponseBody
}

func (o *GetValidationRuleByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetValidationRuleByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetValidationRuleByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetValidationRuleByIDResponse) GetValidationRule() *shared.ValidationRule {
	if o == nil {
		return nil
	}
	return o.ValidationRule
}

func (o *GetValidationRuleByIDResponse) GetFourHundredAndFourApplicationJSONObject() *GetValidationRuleByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *GetValidationRuleByIDResponse) GetFiveHundredApplicationJSONObject() *GetValidationRuleByIDValidationRulesResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}
