// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"net/http"
)

// GetValidationRulesValidationRulesResponseBody - Internal Server Error
type GetValidationRulesValidationRulesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetValidationRulesValidationRulesResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// GetValidationRulesResponseBody - Bad Request - Invalid request body
type GetValidationRulesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GetValidationRulesResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type GetValidationRulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	GetValidationRulesResponse *shared.GetValidationRulesResponse
	// Bad Request - Invalid request body
	FourHundredApplicationJSONObject *GetValidationRulesResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetValidationRulesValidationRulesResponseBody
}

func (o *GetValidationRulesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetValidationRulesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetValidationRulesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetValidationRulesResponse) GetGetValidationRulesResponse() *shared.GetValidationRulesResponse {
	if o == nil {
		return nil
	}
	return o.GetValidationRulesResponse
}

func (o *GetValidationRulesResponse) GetFourHundredApplicationJSONObject() *GetValidationRulesResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *GetValidationRulesResponse) GetFiveHundredApplicationJSONObject() *GetValidationRulesValidationRulesResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}
