// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"net/http"
)

type RemoveUsedByReferenceRequest struct {
	// The unique identifier of the validation rule to update.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
	// The used_by reference to remove
	UsedBy *shared.UsedBy `request:"mediaType=application/json"`
}

func (o *RemoveUsedByReferenceRequest) GetRuleID() string {
	if o == nil {
		return ""
	}
	return o.RuleID
}

func (o *RemoveUsedByReferenceRequest) GetUsedBy() *shared.UsedBy {
	if o == nil {
		return nil
	}
	return o.UsedBy
}

// RemoveUsedByReferenceValidationRulesResponseResponseBody - Internal Server Error
type RemoveUsedByReferenceValidationRulesResponseResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *RemoveUsedByReferenceValidationRulesResponseResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// RemoveUsedByReferenceValidationRulesResponseBody - Validation rule not found
type RemoveUsedByReferenceValidationRulesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *RemoveUsedByReferenceValidationRulesResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// RemoveUsedByReferenceResponseBody - Bad Request - Invalid request body
type RemoveUsedByReferenceResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *RemoveUsedByReferenceResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type RemoveUsedByReferenceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ValidationRule *shared.ValidationRule
	// Bad Request - Invalid request body
	FourHundredApplicationJSONObject *RemoveUsedByReferenceResponseBody
	// Validation rule not found
	FourHundredAndFourApplicationJSONObject *RemoveUsedByReferenceValidationRulesResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *RemoveUsedByReferenceValidationRulesResponseResponseBody
}

func (o *RemoveUsedByReferenceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RemoveUsedByReferenceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RemoveUsedByReferenceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RemoveUsedByReferenceResponse) GetValidationRule() *shared.ValidationRule {
	if o == nil {
		return nil
	}
	return o.ValidationRule
}

func (o *RemoveUsedByReferenceResponse) GetFourHundredApplicationJSONObject() *RemoveUsedByReferenceResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *RemoveUsedByReferenceResponse) GetFourHundredAndFourApplicationJSONObject() *RemoveUsedByReferenceValidationRulesResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *RemoveUsedByReferenceResponse) GetFiveHundredApplicationJSONObject() *RemoveUsedByReferenceValidationRulesResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}
