// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"net/http"
)

type UpdateValidationRuleRequest struct {
	// The unique identifier of the validation rule to update.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
	// Fields to update in the validation rule
	RequestBody *shared.ValidationRuleBase `request:"mediaType=application/json"`
}

func (u *UpdateValidationRuleRequest) GetRuleID() string {
	if u == nil {
		return ""
	}
	return u.RuleID
}

func (u *UpdateValidationRuleRequest) GetRequestBody() *shared.ValidationRuleBase {
	if u == nil {
		return nil
	}
	return u.RequestBody
}

// UpdateValidationRuleValidationRulesResponseBody - Internal Server Error
type UpdateValidationRuleValidationRulesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (u *UpdateValidationRuleValidationRulesResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

// UpdateValidationRuleResponseBody - Bad Request - Invalid request body
type UpdateValidationRuleResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (u *UpdateValidationRuleResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

type UpdateValidationRuleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ValidationRule *shared.ValidationRule
	// Bad Request - Invalid request body
	FourHundredApplicationJSONObject *UpdateValidationRuleResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *UpdateValidationRuleValidationRulesResponseBody
}

func (u *UpdateValidationRuleResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateValidationRuleResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateValidationRuleResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateValidationRuleResponse) GetValidationRule() *shared.ValidationRule {
	if u == nil {
		return nil
	}
	return u.ValidationRule
}

func (u *UpdateValidationRuleResponse) GetFourHundredApplicationJSONObject() *UpdateValidationRuleResponseBody {
	if u == nil {
		return nil
	}
	return u.FourHundredApplicationJSONObject
}

func (u *UpdateValidationRuleResponse) GetFiveHundredApplicationJSONObject() *UpdateValidationRuleValidationRulesResponseBody {
	if u == nil {
		return nil
	}
	return u.FiveHundredApplicationJSONObject
}
