// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"net/http"
)

type UpdateValidationRuleRequest struct {
	// The unique identifier of the validation rule to update.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
	// Fields to update in the validation rule
	RequestBody *shared.ValidationRuleBase `request:"mediaType=application/json"`
}

func (o *UpdateValidationRuleRequest) GetRuleID() string {
	if o == nil {
		return ""
	}
	return o.RuleID
}

func (o *UpdateValidationRuleRequest) GetRequestBody() *shared.ValidationRuleBase {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

// UpdateValidationRuleValidationRulesResponseBody - Internal Server Error
type UpdateValidationRuleValidationRulesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *UpdateValidationRuleValidationRulesResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// UpdateValidationRuleResponseBody - Bad Request - Invalid request body
type UpdateValidationRuleResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *UpdateValidationRuleResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type UpdateValidationRuleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ValidationRule *shared.ValidationRule
	// Bad Request - Invalid request body
	FourHundredApplicationJSONObject *UpdateValidationRuleResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *UpdateValidationRuleValidationRulesResponseBody
}

func (o *UpdateValidationRuleResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateValidationRuleResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateValidationRuleResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateValidationRuleResponse) GetValidationRule() *shared.ValidationRule {
	if o == nil {
		return nil
	}
	return o.ValidationRule
}

func (o *UpdateValidationRuleResponse) GetFourHundredApplicationJSONObject() *UpdateValidationRuleResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *UpdateValidationRuleResponse) GetFiveHundredApplicationJSONObject() *UpdateValidationRuleValidationRulesResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}
