// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type CreateValidationRuleRequestRuleType string

const (
	CreateValidationRuleRequestRuleTypeRegexRuleType   CreateValidationRuleRequestRuleType = "RegexRuleType"
	CreateValidationRuleRequestRuleTypePatternRuleType CreateValidationRuleRequestRuleType = "PatternRuleType"
	CreateValidationRuleRequestRuleTypeNumericRuleType CreateValidationRuleRequestRuleType = "NumericRuleType"
)

type CreateValidationRuleRequestRule struct {
	RegexRuleType   *RegexRuleType   `queryParam:"inline" name:"rule"`
	PatternRuleType *PatternRuleType `queryParam:"inline" name:"rule"`
	NumericRuleType *NumericRuleType `queryParam:"inline" name:"rule"`

	Type CreateValidationRuleRequestRuleType
}

func CreateCreateValidationRuleRequestRuleRegexRuleType(regexRuleType RegexRuleType) CreateValidationRuleRequestRule {
	typ := CreateValidationRuleRequestRuleTypeRegexRuleType

	return CreateValidationRuleRequestRule{
		RegexRuleType: &regexRuleType,
		Type:          typ,
	}
}

func CreateCreateValidationRuleRequestRulePatternRuleType(patternRuleType PatternRuleType) CreateValidationRuleRequestRule {
	typ := CreateValidationRuleRequestRuleTypePatternRuleType

	return CreateValidationRuleRequestRule{
		PatternRuleType: &patternRuleType,
		Type:            typ,
	}
}

func CreateCreateValidationRuleRequestRuleNumericRuleType(numericRuleType NumericRuleType) CreateValidationRuleRequestRule {
	typ := CreateValidationRuleRequestRuleTypeNumericRuleType

	return CreateValidationRuleRequestRule{
		NumericRuleType: &numericRuleType,
		Type:            typ,
	}
}

func (u *CreateValidationRuleRequestRule) UnmarshalJSON(data []byte) error {

	var regexRuleType RegexRuleType = RegexRuleType{}
	if err := utils.UnmarshalJSON(data, &regexRuleType, "", true, nil); err == nil {
		u.RegexRuleType = &regexRuleType
		u.Type = CreateValidationRuleRequestRuleTypeRegexRuleType
		return nil
	}

	var patternRuleType PatternRuleType = PatternRuleType{}
	if err := utils.UnmarshalJSON(data, &patternRuleType, "", true, nil); err == nil {
		u.PatternRuleType = &patternRuleType
		u.Type = CreateValidationRuleRequestRuleTypePatternRuleType
		return nil
	}

	var numericRuleType NumericRuleType = NumericRuleType{}
	if err := utils.UnmarshalJSON(data, &numericRuleType, "", true, nil); err == nil {
		u.NumericRuleType = &numericRuleType
		u.Type = CreateValidationRuleRequestRuleTypeNumericRuleType
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateValidationRuleRequestRule", string(data))
}

func (u CreateValidationRuleRequestRule) MarshalJSON() ([]byte, error) {
	if u.RegexRuleType != nil {
		return utils.MarshalJSON(u.RegexRuleType, "", true)
	}

	if u.PatternRuleType != nil {
		return utils.MarshalJSON(u.PatternRuleType, "", true)
	}

	if u.NumericRuleType != nil {
		return utils.MarshalJSON(u.NumericRuleType, "", true)
	}

	return nil, errors.New("could not marshal union type CreateValidationRuleRequestRule: all fields are null")
}

type CreateValidationRuleRequest struct {
	// Title of the validation rule.
	Title string `json:"title"`
	// Placeholder for the validation rule.
	Placeholder *string                         `json:"placeholder,omitempty"`
	Rule        CreateValidationRuleRequestRule `json:"rule"`
}

func (o *CreateValidationRuleRequest) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *CreateValidationRuleRequest) GetPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.Placeholder
}

func (o *CreateValidationRuleRequest) GetRule() CreateValidationRuleRequestRule {
	if o == nil {
		return CreateValidationRuleRequestRule{}
	}
	return o.Rule
}
