// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type CreateValidationRuleRequestRuleType string

const (
	CreateValidationRuleRequestRuleTypeRegexRuleType   CreateValidationRuleRequestRuleType = "RegexRuleType"
	CreateValidationRuleRequestRuleTypePatternRuleType CreateValidationRuleRequestRuleType = "PatternRuleType"
	CreateValidationRuleRequestRuleTypeNumericRuleType CreateValidationRuleRequestRuleType = "NumericRuleType"
)

type CreateValidationRuleRequestRule struct {
	RegexRuleType   *RegexRuleType   `queryParam:"inline" union:"member"`
	PatternRuleType *PatternRuleType `queryParam:"inline" union:"member"`
	NumericRuleType *NumericRuleType `queryParam:"inline" union:"member"`

	Type CreateValidationRuleRequestRuleType
}

func CreateCreateValidationRuleRequestRuleRegexRuleType(regexRuleType RegexRuleType) CreateValidationRuleRequestRule {
	typ := CreateValidationRuleRequestRuleTypeRegexRuleType

	return CreateValidationRuleRequestRule{
		RegexRuleType: &regexRuleType,
		Type:          typ,
	}
}

func CreateCreateValidationRuleRequestRulePatternRuleType(patternRuleType PatternRuleType) CreateValidationRuleRequestRule {
	typ := CreateValidationRuleRequestRuleTypePatternRuleType

	return CreateValidationRuleRequestRule{
		PatternRuleType: &patternRuleType,
		Type:            typ,
	}
}

func CreateCreateValidationRuleRequestRuleNumericRuleType(numericRuleType NumericRuleType) CreateValidationRuleRequestRule {
	typ := CreateValidationRuleRequestRuleTypeNumericRuleType

	return CreateValidationRuleRequestRule{
		NumericRuleType: &numericRuleType,
		Type:            typ,
	}
}

func (u *CreateValidationRuleRequestRule) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var regexRuleType RegexRuleType = RegexRuleType{}
	if err := utils.UnmarshalJSON(data, &regexRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateValidationRuleRequestRuleTypeRegexRuleType,
			Value: &regexRuleType,
		})
	}

	var patternRuleType PatternRuleType = PatternRuleType{}
	if err := utils.UnmarshalJSON(data, &patternRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateValidationRuleRequestRuleTypePatternRuleType,
			Value: &patternRuleType,
		})
	}

	var numericRuleType NumericRuleType = NumericRuleType{}
	if err := utils.UnmarshalJSON(data, &numericRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateValidationRuleRequestRuleTypeNumericRuleType,
			Value: &numericRuleType,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateValidationRuleRequestRule", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateValidationRuleRequestRule", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CreateValidationRuleRequestRuleType)
	switch best.Type {
	case CreateValidationRuleRequestRuleTypeRegexRuleType:
		u.RegexRuleType = best.Value.(*RegexRuleType)
		return nil
	case CreateValidationRuleRequestRuleTypePatternRuleType:
		u.PatternRuleType = best.Value.(*PatternRuleType)
		return nil
	case CreateValidationRuleRequestRuleTypeNumericRuleType:
		u.NumericRuleType = best.Value.(*NumericRuleType)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateValidationRuleRequestRule", string(data))
}

func (u CreateValidationRuleRequestRule) MarshalJSON() ([]byte, error) {
	if u.RegexRuleType != nil {
		return utils.MarshalJSON(u.RegexRuleType, "", true)
	}

	if u.PatternRuleType != nil {
		return utils.MarshalJSON(u.PatternRuleType, "", true)
	}

	if u.NumericRuleType != nil {
		return utils.MarshalJSON(u.NumericRuleType, "", true)
	}

	return nil, errors.New("could not marshal union type CreateValidationRuleRequestRule: all fields are null")
}

type CreateValidationRuleRequest struct {
	// Title of the validation rule.
	Title string `json:"title"`
	// Placeholder for the validation rule.
	Placeholder *string                         `json:"placeholder,omitempty"`
	Rule        CreateValidationRuleRequestRule `json:"rule"`
}

func (c *CreateValidationRuleRequest) GetTitle() string {
	if c == nil {
		return ""
	}
	return c.Title
}

func (c *CreateValidationRuleRequest) GetPlaceholder() *string {
	if c == nil {
		return nil
	}
	return c.Placeholder
}

func (c *CreateValidationRuleRequest) GetRule() CreateValidationRuleRequestRule {
	if c == nil {
		return CreateValidationRuleRequestRule{}
	}
	return c.Rule
}
