// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetValidationRulesResponse struct {
	Results []ValidationRule `json:"results,omitempty"`
}

func (o *GetValidationRulesResponse) GetResults() []ValidationRule {
	if o == nil {
		return nil
	}
	return o.Results
}
