// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetValidationRulesResponse struct {
	Results []ValidationRule `json:"results,omitempty"`
}

func (g *GetValidationRulesResponse) GetResults() []ValidationRule {
	if g == nil {
		return nil
	}
	return g.Results
}
