// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

// NumericRuleTypeType - Indicates this is a numeric-based validation rule.
type NumericRuleTypeType string

const (
	NumericRuleTypeTypeNumeric NumericRuleTypeType = "numeric"
)

func (e NumericRuleTypeType) ToPointer() *NumericRuleTypeType {
	return &e
}
func (e *NumericRuleTypeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "numeric":
		*e = NumericRuleTypeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NumericRuleTypeType: %v", v)
	}
}

// NumericRuleType - Validation rule for numeric values, supporting range and digit count constraints.
type NumericRuleType struct {
	// Indicates this is a numeric-based validation rule.
	Type NumericRuleTypeType `json:"type"`
	// Condition definition for a numeric-based validation rule (2 levels deep)
	Conditions NumericCondition `json:"conditions"`
}

func (n NumericRuleType) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NumericRuleType) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NumericRuleType) GetType() NumericRuleTypeType {
	if n == nil {
		return NumericRuleTypeType("")
	}
	return n.Type
}

func (n *NumericRuleType) GetConditions() NumericCondition {
	if n == nil {
		return NumericCondition{}
	}
	return n.Conditions
}
