// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type NumericNestedCondition3 struct {
	// Fact-based condition for numeric validation
	Not NumericFactCondition `json:"not"`
}

func (n NumericNestedCondition3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NumericNestedCondition3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, []string{"not"}); err != nil {
		return err
	}
	return nil
}

func (o *NumericNestedCondition3) GetNot() NumericFactCondition {
	if o == nil {
		return NumericFactCondition{}
	}
	return o.Not
}

type NumericNestedCondition2 struct {
	Any []NumericFactCondition `json:"any"`
}

func (n NumericNestedCondition2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NumericNestedCondition2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, []string{"any"}); err != nil {
		return err
	}
	return nil
}

func (o *NumericNestedCondition2) GetAny() []NumericFactCondition {
	if o == nil {
		return []NumericFactCondition{}
	}
	return o.Any
}

type NumericNestedCondition1 struct {
	All []NumericFactCondition `json:"all"`
}

func (n NumericNestedCondition1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NumericNestedCondition1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, []string{"all"}); err != nil {
		return err
	}
	return nil
}

func (o *NumericNestedCondition1) GetAll() []NumericFactCondition {
	if o == nil {
		return []NumericFactCondition{}
	}
	return o.All
}

type NumericNestedConditionType string

const (
	NumericNestedConditionTypeNumericNestedCondition1 NumericNestedConditionType = "NumericNestedCondition_1"
	NumericNestedConditionTypeNumericNestedCondition2 NumericNestedConditionType = "NumericNestedCondition_2"
	NumericNestedConditionTypeNumericNestedCondition3 NumericNestedConditionType = "NumericNestedCondition_3"
)

// NumericNestedCondition - Nested condition with logical operators (level 2 only)
type NumericNestedCondition struct {
	NumericNestedCondition1 *NumericNestedCondition1 `queryParam:"inline" name:"NumericNestedCondition"`
	NumericNestedCondition2 *NumericNestedCondition2 `queryParam:"inline" name:"NumericNestedCondition"`
	NumericNestedCondition3 *NumericNestedCondition3 `queryParam:"inline" name:"NumericNestedCondition"`

	Type NumericNestedConditionType
}

func CreateNumericNestedConditionNumericNestedCondition1(numericNestedCondition1 NumericNestedCondition1) NumericNestedCondition {
	typ := NumericNestedConditionTypeNumericNestedCondition1

	return NumericNestedCondition{
		NumericNestedCondition1: &numericNestedCondition1,
		Type:                    typ,
	}
}

func CreateNumericNestedConditionNumericNestedCondition2(numericNestedCondition2 NumericNestedCondition2) NumericNestedCondition {
	typ := NumericNestedConditionTypeNumericNestedCondition2

	return NumericNestedCondition{
		NumericNestedCondition2: &numericNestedCondition2,
		Type:                    typ,
	}
}

func CreateNumericNestedConditionNumericNestedCondition3(numericNestedCondition3 NumericNestedCondition3) NumericNestedCondition {
	typ := NumericNestedConditionTypeNumericNestedCondition3

	return NumericNestedCondition{
		NumericNestedCondition3: &numericNestedCondition3,
		Type:                    typ,
	}
}

func (u *NumericNestedCondition) UnmarshalJSON(data []byte) error {

	var numericNestedCondition1 NumericNestedCondition1 = NumericNestedCondition1{}
	if err := utils.UnmarshalJSON(data, &numericNestedCondition1, "", true, nil); err == nil {
		u.NumericNestedCondition1 = &numericNestedCondition1
		u.Type = NumericNestedConditionTypeNumericNestedCondition1
		return nil
	}

	var numericNestedCondition2 NumericNestedCondition2 = NumericNestedCondition2{}
	if err := utils.UnmarshalJSON(data, &numericNestedCondition2, "", true, nil); err == nil {
		u.NumericNestedCondition2 = &numericNestedCondition2
		u.Type = NumericNestedConditionTypeNumericNestedCondition2
		return nil
	}

	var numericNestedCondition3 NumericNestedCondition3 = NumericNestedCondition3{}
	if err := utils.UnmarshalJSON(data, &numericNestedCondition3, "", true, nil); err == nil {
		u.NumericNestedCondition3 = &numericNestedCondition3
		u.Type = NumericNestedConditionTypeNumericNestedCondition3
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for NumericNestedCondition", string(data))
}

func (u NumericNestedCondition) MarshalJSON() ([]byte, error) {
	if u.NumericNestedCondition1 != nil {
		return utils.MarshalJSON(u.NumericNestedCondition1, "", true)
	}

	if u.NumericNestedCondition2 != nil {
		return utils.MarshalJSON(u.NumericNestedCondition2, "", true)
	}

	if u.NumericNestedCondition3 != nil {
		return utils.MarshalJSON(u.NumericNestedCondition3, "", true)
	}

	return nil, errors.New("could not marshal union type NumericNestedCondition: all fields are null")
}
