// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

// PatternRuleTypeType - Indicates this is a pattern-based validation rule.
type PatternRuleTypeType string

const (
	PatternRuleTypeTypePattern PatternRuleTypeType = "pattern"
)

func (e PatternRuleTypeType) ToPointer() *PatternRuleTypeType {
	return &e
}
func (e *PatternRuleTypeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pattern":
		*e = PatternRuleTypeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatternRuleTypeType: %v", v)
	}
}

// PatternRuleType - Validation rule that uses a sequence of patterns to validate input.
type PatternRuleType struct {
	// Indicates this is a pattern-based validation rule.
	Type PatternRuleTypeType `json:"type"`
	// Condition definition for a pattern-based validation rule (2 levels deep)
	Conditions PatternCondition `json:"conditions"`
}

func (p PatternRuleType) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatternRuleType) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatternRuleType) GetType() PatternRuleTypeType {
	if p == nil {
		return PatternRuleTypeType("")
	}
	return p.Type
}

func (p *PatternRuleType) GetConditions() PatternCondition {
	if p == nil {
		return PatternCondition{}
	}
	return p.Conditions
}
