// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type PatternNestedCondition3 struct {
	// Fact-based condition for pattern validation
	Not PatternFactCondition `json:"not"`
}

func (p PatternNestedCondition3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatternNestedCondition3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"not"}); err != nil {
		return err
	}
	return nil
}

func (o *PatternNestedCondition3) GetNot() PatternFactCondition {
	if o == nil {
		return PatternFactCondition{}
	}
	return o.Not
}

type PatternNestedCondition2 struct {
	Any []PatternFactCondition `json:"any"`
}

func (p PatternNestedCondition2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatternNestedCondition2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"any"}); err != nil {
		return err
	}
	return nil
}

func (o *PatternNestedCondition2) GetAny() []PatternFactCondition {
	if o == nil {
		return []PatternFactCondition{}
	}
	return o.Any
}

type PatternNestedCondition1 struct {
	All []PatternFactCondition `json:"all"`
}

func (p PatternNestedCondition1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatternNestedCondition1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"all"}); err != nil {
		return err
	}
	return nil
}

func (o *PatternNestedCondition1) GetAll() []PatternFactCondition {
	if o == nil {
		return []PatternFactCondition{}
	}
	return o.All
}

type PatternNestedConditionType string

const (
	PatternNestedConditionTypePatternNestedCondition1 PatternNestedConditionType = "PatternNestedCondition_1"
	PatternNestedConditionTypePatternNestedCondition2 PatternNestedConditionType = "PatternNestedCondition_2"
	PatternNestedConditionTypePatternNestedCondition3 PatternNestedConditionType = "PatternNestedCondition_3"
)

// PatternNestedCondition - Nested condition with logical operators (level 2 only)
type PatternNestedCondition struct {
	PatternNestedCondition1 *PatternNestedCondition1 `queryParam:"inline" name:"PatternNestedCondition"`
	PatternNestedCondition2 *PatternNestedCondition2 `queryParam:"inline" name:"PatternNestedCondition"`
	PatternNestedCondition3 *PatternNestedCondition3 `queryParam:"inline" name:"PatternNestedCondition"`

	Type PatternNestedConditionType
}

func CreatePatternNestedConditionPatternNestedCondition1(patternNestedCondition1 PatternNestedCondition1) PatternNestedCondition {
	typ := PatternNestedConditionTypePatternNestedCondition1

	return PatternNestedCondition{
		PatternNestedCondition1: &patternNestedCondition1,
		Type:                    typ,
	}
}

func CreatePatternNestedConditionPatternNestedCondition2(patternNestedCondition2 PatternNestedCondition2) PatternNestedCondition {
	typ := PatternNestedConditionTypePatternNestedCondition2

	return PatternNestedCondition{
		PatternNestedCondition2: &patternNestedCondition2,
		Type:                    typ,
	}
}

func CreatePatternNestedConditionPatternNestedCondition3(patternNestedCondition3 PatternNestedCondition3) PatternNestedCondition {
	typ := PatternNestedConditionTypePatternNestedCondition3

	return PatternNestedCondition{
		PatternNestedCondition3: &patternNestedCondition3,
		Type:                    typ,
	}
}

func (u *PatternNestedCondition) UnmarshalJSON(data []byte) error {

	var patternNestedCondition1 PatternNestedCondition1 = PatternNestedCondition1{}
	if err := utils.UnmarshalJSON(data, &patternNestedCondition1, "", true, nil); err == nil {
		u.PatternNestedCondition1 = &patternNestedCondition1
		u.Type = PatternNestedConditionTypePatternNestedCondition1
		return nil
	}

	var patternNestedCondition2 PatternNestedCondition2 = PatternNestedCondition2{}
	if err := utils.UnmarshalJSON(data, &patternNestedCondition2, "", true, nil); err == nil {
		u.PatternNestedCondition2 = &patternNestedCondition2
		u.Type = PatternNestedConditionTypePatternNestedCondition2
		return nil
	}

	var patternNestedCondition3 PatternNestedCondition3 = PatternNestedCondition3{}
	if err := utils.UnmarshalJSON(data, &patternNestedCondition3, "", true, nil); err == nil {
		u.PatternNestedCondition3 = &patternNestedCondition3
		u.Type = PatternNestedConditionTypePatternNestedCondition3
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PatternNestedCondition", string(data))
}

func (u PatternNestedCondition) MarshalJSON() ([]byte, error) {
	if u.PatternNestedCondition1 != nil {
		return utils.MarshalJSON(u.PatternNestedCondition1, "", true)
	}

	if u.PatternNestedCondition2 != nil {
		return utils.MarshalJSON(u.PatternNestedCondition2, "", true)
	}

	if u.PatternNestedCondition3 != nil {
		return utils.MarshalJSON(u.PatternNestedCondition3, "", true)
	}

	return nil, errors.New("could not marshal union type PatternNestedCondition: all fields are null")
}
