// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type PatternNestedCondition3 struct {
	// Fact-based condition for pattern validation
	Not PatternFactCondition `json:"not"`
}

func (p PatternNestedCondition3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatternNestedCondition3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatternNestedCondition3) GetNot() PatternFactCondition {
	if p == nil {
		return PatternFactCondition{}
	}
	return p.Not
}

type PatternNestedCondition2 struct {
	Any []PatternFactCondition `json:"any"`
}

func (p PatternNestedCondition2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatternNestedCondition2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatternNestedCondition2) GetAny() []PatternFactCondition {
	if p == nil {
		return []PatternFactCondition{}
	}
	return p.Any
}

type PatternNestedCondition1 struct {
	All []PatternFactCondition `json:"all"`
}

func (p PatternNestedCondition1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatternNestedCondition1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatternNestedCondition1) GetAll() []PatternFactCondition {
	if p == nil {
		return []PatternFactCondition{}
	}
	return p.All
}

type PatternNestedConditionType string

const (
	PatternNestedConditionTypePatternNestedCondition1 PatternNestedConditionType = "PatternNestedCondition_1"
	PatternNestedConditionTypePatternNestedCondition2 PatternNestedConditionType = "PatternNestedCondition_2"
	PatternNestedConditionTypePatternNestedCondition3 PatternNestedConditionType = "PatternNestedCondition_3"
)

// PatternNestedCondition - Nested condition with logical operators (level 2 only)
type PatternNestedCondition struct {
	PatternNestedCondition1 *PatternNestedCondition1 `queryParam:"inline" union:"member"`
	PatternNestedCondition2 *PatternNestedCondition2 `queryParam:"inline" union:"member"`
	PatternNestedCondition3 *PatternNestedCondition3 `queryParam:"inline" union:"member"`

	Type PatternNestedConditionType
}

func CreatePatternNestedConditionPatternNestedCondition1(patternNestedCondition1 PatternNestedCondition1) PatternNestedCondition {
	typ := PatternNestedConditionTypePatternNestedCondition1

	return PatternNestedCondition{
		PatternNestedCondition1: &patternNestedCondition1,
		Type:                    typ,
	}
}

func CreatePatternNestedConditionPatternNestedCondition2(patternNestedCondition2 PatternNestedCondition2) PatternNestedCondition {
	typ := PatternNestedConditionTypePatternNestedCondition2

	return PatternNestedCondition{
		PatternNestedCondition2: &patternNestedCondition2,
		Type:                    typ,
	}
}

func CreatePatternNestedConditionPatternNestedCondition3(patternNestedCondition3 PatternNestedCondition3) PatternNestedCondition {
	typ := PatternNestedConditionTypePatternNestedCondition3

	return PatternNestedCondition{
		PatternNestedCondition3: &patternNestedCondition3,
		Type:                    typ,
	}
}

func (u *PatternNestedCondition) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var patternNestedCondition1 PatternNestedCondition1 = PatternNestedCondition1{}
	if err := utils.UnmarshalJSON(data, &patternNestedCondition1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PatternNestedConditionTypePatternNestedCondition1,
			Value: &patternNestedCondition1,
		})
	}

	var patternNestedCondition2 PatternNestedCondition2 = PatternNestedCondition2{}
	if err := utils.UnmarshalJSON(data, &patternNestedCondition2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PatternNestedConditionTypePatternNestedCondition2,
			Value: &patternNestedCondition2,
		})
	}

	var patternNestedCondition3 PatternNestedCondition3 = PatternNestedCondition3{}
	if err := utils.UnmarshalJSON(data, &patternNestedCondition3, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PatternNestedConditionTypePatternNestedCondition3,
			Value: &patternNestedCondition3,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PatternNestedCondition", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PatternNestedCondition", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PatternNestedConditionType)
	switch best.Type {
	case PatternNestedConditionTypePatternNestedCondition1:
		u.PatternNestedCondition1 = best.Value.(*PatternNestedCondition1)
		return nil
	case PatternNestedConditionTypePatternNestedCondition2:
		u.PatternNestedCondition2 = best.Value.(*PatternNestedCondition2)
		return nil
	case PatternNestedConditionTypePatternNestedCondition3:
		u.PatternNestedCondition3 = best.Value.(*PatternNestedCondition3)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PatternNestedCondition", string(data))
}

func (u PatternNestedCondition) MarshalJSON() ([]byte, error) {
	if u.PatternNestedCondition1 != nil {
		return utils.MarshalJSON(u.PatternNestedCondition1, "", true)
	}

	if u.PatternNestedCondition2 != nil {
		return utils.MarshalJSON(u.PatternNestedCondition2, "", true)
	}

	if u.PatternNestedCondition3 != nil {
		return utils.MarshalJSON(u.PatternNestedCondition3, "", true)
	}

	return nil, errors.New("could not marshal union type PatternNestedCondition: all fields are null")
}
