// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type Three struct {
	// Fact-based condition for regex validation
	Not RegexFactCondition `json:"not"`
}

func (t Three) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Three) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Three) GetNot() RegexFactCondition {
	if t == nil {
		return RegexFactCondition{}
	}
	return t.Not
}

type Two struct {
	Any []RegexFactCondition `json:"any"`
}

func (t Two) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Two) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Two) GetAny() []RegexFactCondition {
	if t == nil {
		return []RegexFactCondition{}
	}
	return t.Any
}

type One struct {
	All []RegexFactCondition `json:"all"`
}

func (o One) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *One) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *One) GetAll() []RegexFactCondition {
	if o == nil {
		return []RegexFactCondition{}
	}
	return o.All
}

type RegexNestedConditionType string

const (
	RegexNestedConditionTypeOne   RegexNestedConditionType = "1"
	RegexNestedConditionTypeTwo   RegexNestedConditionType = "2"
	RegexNestedConditionTypeThree RegexNestedConditionType = "3"
)

// RegexNestedCondition - Nested condition with logical operators (level 2 only)
type RegexNestedCondition struct {
	One   *One   `queryParam:"inline" union:"member"`
	Two   *Two   `queryParam:"inline" union:"member"`
	Three *Three `queryParam:"inline" union:"member"`

	Type RegexNestedConditionType
}

func CreateRegexNestedConditionOne(one One) RegexNestedCondition {
	typ := RegexNestedConditionTypeOne

	return RegexNestedCondition{
		One:  &one,
		Type: typ,
	}
}

func CreateRegexNestedConditionTwo(two Two) RegexNestedCondition {
	typ := RegexNestedConditionTypeTwo

	return RegexNestedCondition{
		Two:  &two,
		Type: typ,
	}
}

func CreateRegexNestedConditionThree(three Three) RegexNestedCondition {
	typ := RegexNestedConditionTypeThree

	return RegexNestedCondition{
		Three: &three,
		Type:  typ,
	}
}

func (u *RegexNestedCondition) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var one One = One{}
	if err := utils.UnmarshalJSON(data, &one, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RegexNestedConditionTypeOne,
			Value: &one,
		})
	}

	var two Two = Two{}
	if err := utils.UnmarshalJSON(data, &two, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RegexNestedConditionTypeTwo,
			Value: &two,
		})
	}

	var three Three = Three{}
	if err := utils.UnmarshalJSON(data, &three, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RegexNestedConditionTypeThree,
			Value: &three,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for RegexNestedCondition", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for RegexNestedCondition", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(RegexNestedConditionType)
	switch best.Type {
	case RegexNestedConditionTypeOne:
		u.One = best.Value.(*One)
		return nil
	case RegexNestedConditionTypeTwo:
		u.Two = best.Value.(*Two)
		return nil
	case RegexNestedConditionTypeThree:
		u.Three = best.Value.(*Three)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RegexNestedCondition", string(data))
}

func (u RegexNestedCondition) MarshalJSON() ([]byte, error) {
	if u.One != nil {
		return utils.MarshalJSON(u.One, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	if u.Three != nil {
		return utils.MarshalJSON(u.Three, "", true)
	}

	return nil, errors.New("could not marshal union type RegexNestedCondition: all fields are null")
}
