// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

// Fact - The name of the value to validate. Should always be 'inputValue' because this property name is passed to the engine
type Fact string

const (
	FactInputValue Fact = "inputValue"
)

func (e Fact) ToPointer() *Fact {
	return &e
}
func (e *Fact) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inputValue":
		*e = Fact(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Fact: %v", v)
	}
}

// Operator - The operator to use for comparison
type Operator string

const (
	OperatorRegexMatch Operator = "regexMatch"
)

func (e Operator) ToPointer() *Operator {
	return &e
}
func (e *Operator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "regexMatch":
		*e = Operator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Operator: %v", v)
	}
}

// Params - Additional parameters for the condition
type Params struct {
	// Custom error message
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

func (p Params) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Params) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Params) GetErrorMessage() *string {
	if p == nil {
		return nil
	}
	return p.ErrorMessage
}

// RegexFactCondition - Fact-based condition for regex validation
type RegexFactCondition struct {
	// The name of the value to validate. Should always be 'inputValue' because this property name is passed to the engine
	Fact Fact `json:"fact"`
	// The operator to use for comparison
	Operator Operator `json:"operator"`
	// Additional parameters for the condition
	Params *Params `json:"params,omitempty"`
	// The actual regex
	Value string `json:"value"`
}

func (r RegexFactCondition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegexFactCondition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RegexFactCondition) GetFact() Fact {
	if r == nil {
		return Fact("")
	}
	return r.Fact
}

func (r *RegexFactCondition) GetOperator() Operator {
	if r == nil {
		return Operator("")
	}
	return r.Operator
}

func (r *RegexFactCondition) GetParams() *Params {
	if r == nil {
		return nil
	}
	return r.Params
}

func (r *RegexFactCondition) GetValue() string {
	if r == nil {
		return ""
	}
	return r.Value
}
