// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type Three struct {
	// Fact-based condition for regex validation
	Not RegexFactCondition `json:"not"`
}

func (t Three) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Three) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"not"}); err != nil {
		return err
	}
	return nil
}

func (o *Three) GetNot() RegexFactCondition {
	if o == nil {
		return RegexFactCondition{}
	}
	return o.Not
}

type Two struct {
	Any []RegexFactCondition `json:"any"`
}

func (t Two) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Two) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"any"}); err != nil {
		return err
	}
	return nil
}

func (o *Two) GetAny() []RegexFactCondition {
	if o == nil {
		return []RegexFactCondition{}
	}
	return o.Any
}

type One struct {
	All []RegexFactCondition `json:"all"`
}

func (o One) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *One) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, []string{"all"}); err != nil {
		return err
	}
	return nil
}

func (o *One) GetAll() []RegexFactCondition {
	if o == nil {
		return []RegexFactCondition{}
	}
	return o.All
}

type RegexNestedConditionType string

const (
	RegexNestedConditionTypeOne   RegexNestedConditionType = "1"
	RegexNestedConditionTypeTwo   RegexNestedConditionType = "2"
	RegexNestedConditionTypeThree RegexNestedConditionType = "3"
)

// RegexNestedCondition - Nested condition with logical operators (level 2 only)
type RegexNestedCondition struct {
	One   *One   `queryParam:"inline" name:"RegexNestedCondition"`
	Two   *Two   `queryParam:"inline" name:"RegexNestedCondition"`
	Three *Three `queryParam:"inline" name:"RegexNestedCondition"`

	Type RegexNestedConditionType
}

func CreateRegexNestedConditionOne(one One) RegexNestedCondition {
	typ := RegexNestedConditionTypeOne

	return RegexNestedCondition{
		One:  &one,
		Type: typ,
	}
}

func CreateRegexNestedConditionTwo(two Two) RegexNestedCondition {
	typ := RegexNestedConditionTypeTwo

	return RegexNestedCondition{
		Two:  &two,
		Type: typ,
	}
}

func CreateRegexNestedConditionThree(three Three) RegexNestedCondition {
	typ := RegexNestedConditionTypeThree

	return RegexNestedCondition{
		Three: &three,
		Type:  typ,
	}
}

func (u *RegexNestedCondition) UnmarshalJSON(data []byte) error {

	var one One = One{}
	if err := utils.UnmarshalJSON(data, &one, "", true, nil); err == nil {
		u.One = &one
		u.Type = RegexNestedConditionTypeOne
		return nil
	}

	var two Two = Two{}
	if err := utils.UnmarshalJSON(data, &two, "", true, nil); err == nil {
		u.Two = &two
		u.Type = RegexNestedConditionTypeTwo
		return nil
	}

	var three Three = Three{}
	if err := utils.UnmarshalJSON(data, &three, "", true, nil); err == nil {
		u.Three = &three
		u.Type = RegexNestedConditionTypeThree
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RegexNestedCondition", string(data))
}

func (u RegexNestedCondition) MarshalJSON() ([]byte, error) {
	if u.One != nil {
		return utils.MarshalJSON(u.One, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	if u.Three != nil {
		return utils.MarshalJSON(u.Three, "", true)
	}

	return nil, errors.New("could not marshal union type RegexNestedCondition: all fields are null")
}
