// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

// RegexRuleTypeType - Indicates this is a regex-based validation rule.
type RegexRuleTypeType string

const (
	RegexRuleTypeTypeRegex RegexRuleTypeType = "regex"
)

func (e RegexRuleTypeType) ToPointer() *RegexRuleTypeType {
	return &e
}
func (e *RegexRuleTypeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "regex":
		*e = RegexRuleTypeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RegexRuleTypeType: %v", v)
	}
}

// RegexRuleType - Validation rule that uses a regular expression to validate input.
type RegexRuleType struct {
	// Indicates this is a regex-based validation rule.
	Type RegexRuleTypeType `json:"type"`
	// Condition definition for a regex-based validation rule (2 levels deep)
	Conditions RegexCondition `json:"conditions"`
}

func (r RegexRuleType) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegexRuleType) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"type", "conditions"}); err != nil {
		return err
	}
	return nil
}

func (o *RegexRuleType) GetType() RegexRuleTypeType {
	if o == nil {
		return RegexRuleTypeType("")
	}
	return o.Type
}

func (o *RegexRuleType) GetConditions() RegexCondition {
	if o == nil {
		return RegexCondition{}
	}
	return o.Conditions
}
