// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type ValidationRuleBaseRuleType string

const (
	ValidationRuleBaseRuleTypeRegexRuleType   ValidationRuleBaseRuleType = "RegexRuleType"
	ValidationRuleBaseRuleTypePatternRuleType ValidationRuleBaseRuleType = "PatternRuleType"
	ValidationRuleBaseRuleTypeNumericRuleType ValidationRuleBaseRuleType = "NumericRuleType"
)

type ValidationRuleBaseRule struct {
	RegexRuleType   *RegexRuleType   `queryParam:"inline" union:"member"`
	PatternRuleType *PatternRuleType `queryParam:"inline" union:"member"`
	NumericRuleType *NumericRuleType `queryParam:"inline" union:"member"`

	Type ValidationRuleBaseRuleType
}

func CreateValidationRuleBaseRuleRegexRuleType(regexRuleType RegexRuleType) ValidationRuleBaseRule {
	typ := ValidationRuleBaseRuleTypeRegexRuleType

	return ValidationRuleBaseRule{
		RegexRuleType: &regexRuleType,
		Type:          typ,
	}
}

func CreateValidationRuleBaseRulePatternRuleType(patternRuleType PatternRuleType) ValidationRuleBaseRule {
	typ := ValidationRuleBaseRuleTypePatternRuleType

	return ValidationRuleBaseRule{
		PatternRuleType: &patternRuleType,
		Type:            typ,
	}
}

func CreateValidationRuleBaseRuleNumericRuleType(numericRuleType NumericRuleType) ValidationRuleBaseRule {
	typ := ValidationRuleBaseRuleTypeNumericRuleType

	return ValidationRuleBaseRule{
		NumericRuleType: &numericRuleType,
		Type:            typ,
	}
}

func (u *ValidationRuleBaseRule) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var regexRuleType RegexRuleType = RegexRuleType{}
	if err := utils.UnmarshalJSON(data, &regexRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValidationRuleBaseRuleTypeRegexRuleType,
			Value: &regexRuleType,
		})
	}

	var patternRuleType PatternRuleType = PatternRuleType{}
	if err := utils.UnmarshalJSON(data, &patternRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValidationRuleBaseRuleTypePatternRuleType,
			Value: &patternRuleType,
		})
	}

	var numericRuleType NumericRuleType = NumericRuleType{}
	if err := utils.UnmarshalJSON(data, &numericRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValidationRuleBaseRuleTypeNumericRuleType,
			Value: &numericRuleType,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValidationRuleBaseRule", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValidationRuleBaseRule", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ValidationRuleBaseRuleType)
	switch best.Type {
	case ValidationRuleBaseRuleTypeRegexRuleType:
		u.RegexRuleType = best.Value.(*RegexRuleType)
		return nil
	case ValidationRuleBaseRuleTypePatternRuleType:
		u.PatternRuleType = best.Value.(*PatternRuleType)
		return nil
	case ValidationRuleBaseRuleTypeNumericRuleType:
		u.NumericRuleType = best.Value.(*NumericRuleType)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValidationRuleBaseRule", string(data))
}

func (u ValidationRuleBaseRule) MarshalJSON() ([]byte, error) {
	if u.RegexRuleType != nil {
		return utils.MarshalJSON(u.RegexRuleType, "", true)
	}

	if u.PatternRuleType != nil {
		return utils.MarshalJSON(u.PatternRuleType, "", true)
	}

	if u.NumericRuleType != nil {
		return utils.MarshalJSON(u.NumericRuleType, "", true)
	}

	return nil, errors.New("could not marshal union type ValidationRuleBaseRule: all fields are null")
}

type ValidationRuleBase struct {
	// Title of the validation rule.
	Title *string `json:"title,omitempty"`
	// Placeholder for the validation rule.
	Placeholder *string                 `json:"placeholder,omitempty"`
	Rule        *ValidationRuleBaseRule `json:"rule,omitempty"`
}

func (v *ValidationRuleBase) GetTitle() *string {
	if v == nil {
		return nil
	}
	return v.Title
}

func (v *ValidationRuleBase) GetPlaceholder() *string {
	if v == nil {
		return nil
	}
	return v.Placeholder
}

func (v *ValidationRuleBase) GetRule() *ValidationRuleBaseRule {
	if v == nil {
		return nil
	}
	return v.Rule
}
