// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type ValidationRuleBaseRuleType string

const (
	ValidationRuleBaseRuleTypeRegexRuleType   ValidationRuleBaseRuleType = "RegexRuleType"
	ValidationRuleBaseRuleTypePatternRuleType ValidationRuleBaseRuleType = "PatternRuleType"
	ValidationRuleBaseRuleTypeNumericRuleType ValidationRuleBaseRuleType = "NumericRuleType"
)

type ValidationRuleBaseRule struct {
	RegexRuleType   *RegexRuleType   `queryParam:"inline" name:"rule"`
	PatternRuleType *PatternRuleType `queryParam:"inline" name:"rule"`
	NumericRuleType *NumericRuleType `queryParam:"inline" name:"rule"`

	Type ValidationRuleBaseRuleType
}

func CreateValidationRuleBaseRuleRegexRuleType(regexRuleType RegexRuleType) ValidationRuleBaseRule {
	typ := ValidationRuleBaseRuleTypeRegexRuleType

	return ValidationRuleBaseRule{
		RegexRuleType: &regexRuleType,
		Type:          typ,
	}
}

func CreateValidationRuleBaseRulePatternRuleType(patternRuleType PatternRuleType) ValidationRuleBaseRule {
	typ := ValidationRuleBaseRuleTypePatternRuleType

	return ValidationRuleBaseRule{
		PatternRuleType: &patternRuleType,
		Type:            typ,
	}
}

func CreateValidationRuleBaseRuleNumericRuleType(numericRuleType NumericRuleType) ValidationRuleBaseRule {
	typ := ValidationRuleBaseRuleTypeNumericRuleType

	return ValidationRuleBaseRule{
		NumericRuleType: &numericRuleType,
		Type:            typ,
	}
}

func (u *ValidationRuleBaseRule) UnmarshalJSON(data []byte) error {

	var regexRuleType RegexRuleType = RegexRuleType{}
	if err := utils.UnmarshalJSON(data, &regexRuleType, "", true, nil); err == nil {
		u.RegexRuleType = &regexRuleType
		u.Type = ValidationRuleBaseRuleTypeRegexRuleType
		return nil
	}

	var patternRuleType PatternRuleType = PatternRuleType{}
	if err := utils.UnmarshalJSON(data, &patternRuleType, "", true, nil); err == nil {
		u.PatternRuleType = &patternRuleType
		u.Type = ValidationRuleBaseRuleTypePatternRuleType
		return nil
	}

	var numericRuleType NumericRuleType = NumericRuleType{}
	if err := utils.UnmarshalJSON(data, &numericRuleType, "", true, nil); err == nil {
		u.NumericRuleType = &numericRuleType
		u.Type = ValidationRuleBaseRuleTypeNumericRuleType
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValidationRuleBaseRule", string(data))
}

func (u ValidationRuleBaseRule) MarshalJSON() ([]byte, error) {
	if u.RegexRuleType != nil {
		return utils.MarshalJSON(u.RegexRuleType, "", true)
	}

	if u.PatternRuleType != nil {
		return utils.MarshalJSON(u.PatternRuleType, "", true)
	}

	if u.NumericRuleType != nil {
		return utils.MarshalJSON(u.NumericRuleType, "", true)
	}

	return nil, errors.New("could not marshal union type ValidationRuleBaseRule: all fields are null")
}

type ValidationRuleBase struct {
	// Title of the validation rule.
	Title *string `json:"title,omitempty"`
	// Placeholder for the validation rule.
	Placeholder *string `json:"placeholder,omitempty"`
	// Describes where and how a validation rule is applied.
	UsedBy []UsedBy                `json:"used_by,omitempty"`
	Rule   *ValidationRuleBaseRule `json:"rule,omitempty"`
}

func (o *ValidationRuleBase) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *ValidationRuleBase) GetPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.Placeholder
}

func (o *ValidationRuleBase) GetUsedBy() []UsedBy {
	if o == nil {
		return nil
	}
	return o.UsedBy
}

func (o *ValidationRuleBase) GetRule() *ValidationRuleBaseRule {
	if o == nil {
		return nil
	}
	return o.Rule
}
