// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// UsedByType - The context in which the rule is used (e.g., journey or entity).
type UsedByType string

const (
	UsedByTypeJourney UsedByType = "journey"
	UsedByTypeEntity  UsedByType = "entity"
)

func (e UsedByType) ToPointer() *UsedByType {
	return &e
}
func (e *UsedByType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey":
		fallthrough
	case "entity":
		*e = UsedByType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UsedByType: %v", v)
	}
}

// UsedBy - Describes where and how a validation rule is applied.
type UsedBy struct {
	// The context in which the rule is used (e.g., journey or entity).
	Type UsedByType `json:"type"`
	// Slug of the schema using this rule for entities.
	SchemaSlug *string `json:"schema_slug,omitempty"`
	// Source identifier for the usage context.
	SourceID *string `json:"source_id,omitempty"`
}

func (o *UsedBy) GetType() UsedByType {
	if o == nil {
		return UsedByType("")
	}
	return o.Type
}

func (o *UsedBy) GetSchemaSlug() *string {
	if o == nil {
		return nil
	}
	return o.SchemaSlug
}

func (o *UsedBy) GetSourceID() *string {
	if o == nil {
		return nil
	}
	return o.SourceID
}
