// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Type - The context in which the rule is used (e.g., journey or entity).
type Type string

const (
	TypeJourney Type = "journey"
	TypeEntity  Type = "entity"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey":
		fallthrough
	case "entity":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

// UsedBy - Describes where and how a validation rule is applied.
type UsedBy struct {
	// The context in which the rule is used (e.g., journey or entity).
	Type Type `json:"type"`
	// Slug of the schema using this rule for entities.
	SchemaSlug *string `json:"schema_slug,omitempty"`
	// Source identifier for the usage context.
	SourceID *string `json:"source_id,omitempty"`
}

func (o *UsedBy) GetType() Type {
	if o == nil {
		return Type("")
	}
	return o.Type
}

func (o *UsedBy) GetSchemaSlug() *string {
	if o == nil {
		return nil
	}
	return o.SchemaSlug
}

func (o *UsedBy) GetSourceID() *string {
	if o == nil {
		return nil
	}
	return o.SourceID
}
