// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type RuleType string

const (
	RuleTypeRegexRuleType   RuleType = "RegexRuleType"
	RuleTypePatternRuleType RuleType = "PatternRuleType"
	RuleTypeNumericRuleType RuleType = "NumericRuleType"
)

type Rule struct {
	RegexRuleType   *RegexRuleType   `queryParam:"inline" union:"member"`
	PatternRuleType *PatternRuleType `queryParam:"inline" union:"member"`
	NumericRuleType *NumericRuleType `queryParam:"inline" union:"member"`

	Type RuleType
}

func CreateRuleRegexRuleType(regexRuleType RegexRuleType) Rule {
	typ := RuleTypeRegexRuleType

	return Rule{
		RegexRuleType: &regexRuleType,
		Type:          typ,
	}
}

func CreateRulePatternRuleType(patternRuleType PatternRuleType) Rule {
	typ := RuleTypePatternRuleType

	return Rule{
		PatternRuleType: &patternRuleType,
		Type:            typ,
	}
}

func CreateRuleNumericRuleType(numericRuleType NumericRuleType) Rule {
	typ := RuleTypeNumericRuleType

	return Rule{
		NumericRuleType: &numericRuleType,
		Type:            typ,
	}
}

func (u *Rule) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var regexRuleType RegexRuleType = RegexRuleType{}
	if err := utils.UnmarshalJSON(data, &regexRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RuleTypeRegexRuleType,
			Value: &regexRuleType,
		})
	}

	var patternRuleType PatternRuleType = PatternRuleType{}
	if err := utils.UnmarshalJSON(data, &patternRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RuleTypePatternRuleType,
			Value: &patternRuleType,
		})
	}

	var numericRuleType NumericRuleType = NumericRuleType{}
	if err := utils.UnmarshalJSON(data, &numericRuleType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RuleTypeNumericRuleType,
			Value: &numericRuleType,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Rule", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Rule", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(RuleType)
	switch best.Type {
	case RuleTypeRegexRuleType:
		u.RegexRuleType = best.Value.(*RegexRuleType)
		return nil
	case RuleTypePatternRuleType:
		u.PatternRuleType = best.Value.(*PatternRuleType)
		return nil
	case RuleTypeNumericRuleType:
		u.NumericRuleType = best.Value.(*NumericRuleType)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Rule", string(data))
}

func (u Rule) MarshalJSON() ([]byte, error) {
	if u.RegexRuleType != nil {
		return utils.MarshalJSON(u.RegexRuleType, "", true)
	}

	if u.PatternRuleType != nil {
		return utils.MarshalJSON(u.PatternRuleType, "", true)
	}

	if u.NumericRuleType != nil {
		return utils.MarshalJSON(u.NumericRuleType, "", true)
	}

	return nil, errors.New("could not marshal union type Rule: all fields are null")
}

// ValidationRule - The Validation rule definition.
type ValidationRule struct {
	// Title of the validation rule.
	Title string `json:"title"`
	// Placeholder for the validation rule.
	Placeholder *string `json:"placeholder,omitempty"`
	Rule        *Rule   `json:"rule,omitempty"`
	// Schema version of the validation rule.
	SchemaVersion string `json:"_schema_version"`
	// Unique identifier for the validation rule.
	ID string `json:"_id"`
	// Organization ID that owns this rule.
	OrganizationID string `json:"_organization_id"`
	// ISO timestamp when the rule was created.
	CreatedAt string `json:"created_at"`
	// ISO timestamp when the rule was last updated.
	UpdatedAt string `json:"updated_at"`
	// User ID of the creator.
	CreatedBy string `json:"created_by"`
	// User ID of the last updater.
	UpdatedBy string `json:"updated_by"`
}

func (v *ValidationRule) GetTitle() string {
	if v == nil {
		return ""
	}
	return v.Title
}

func (v *ValidationRule) GetPlaceholder() *string {
	if v == nil {
		return nil
	}
	return v.Placeholder
}

func (v *ValidationRule) GetRule() *Rule {
	if v == nil {
		return nil
	}
	return v.Rule
}

func (v *ValidationRule) GetSchemaVersion() string {
	if v == nil {
		return ""
	}
	return v.SchemaVersion
}

func (v *ValidationRule) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *ValidationRule) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *ValidationRule) GetCreatedAt() string {
	if v == nil {
		return ""
	}
	return v.CreatedAt
}

func (v *ValidationRule) GetUpdatedAt() string {
	if v == nil {
		return ""
	}
	return v.UpdatedAt
}

func (v *ValidationRule) GetCreatedBy() string {
	if v == nil {
		return ""
	}
	return v.CreatedBy
}

func (v *ValidationRule) GetUpdatedBy() string {
	if v == nil {
		return ""
	}
	return v.UpdatedBy
}
