// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/internal/utils"
)

type RuleType string

const (
	RuleTypeRegexRuleType   RuleType = "RegexRuleType"
	RuleTypePatternRuleType RuleType = "PatternRuleType"
	RuleTypeNumericRuleType RuleType = "NumericRuleType"
)

type Rule struct {
	RegexRuleType   *RegexRuleType   `queryParam:"inline" name:"rule"`
	PatternRuleType *PatternRuleType `queryParam:"inline" name:"rule"`
	NumericRuleType *NumericRuleType `queryParam:"inline" name:"rule"`

	Type RuleType
}

func CreateRuleRegexRuleType(regexRuleType RegexRuleType) Rule {
	typ := RuleTypeRegexRuleType

	return Rule{
		RegexRuleType: &regexRuleType,
		Type:          typ,
	}
}

func CreateRulePatternRuleType(patternRuleType PatternRuleType) Rule {
	typ := RuleTypePatternRuleType

	return Rule{
		PatternRuleType: &patternRuleType,
		Type:            typ,
	}
}

func CreateRuleNumericRuleType(numericRuleType NumericRuleType) Rule {
	typ := RuleTypeNumericRuleType

	return Rule{
		NumericRuleType: &numericRuleType,
		Type:            typ,
	}
}

func (u *Rule) UnmarshalJSON(data []byte) error {

	var regexRuleType RegexRuleType = RegexRuleType{}
	if err := utils.UnmarshalJSON(data, &regexRuleType, "", true, nil); err == nil {
		u.RegexRuleType = &regexRuleType
		u.Type = RuleTypeRegexRuleType
		return nil
	}

	var patternRuleType PatternRuleType = PatternRuleType{}
	if err := utils.UnmarshalJSON(data, &patternRuleType, "", true, nil); err == nil {
		u.PatternRuleType = &patternRuleType
		u.Type = RuleTypePatternRuleType
		return nil
	}

	var numericRuleType NumericRuleType = NumericRuleType{}
	if err := utils.UnmarshalJSON(data, &numericRuleType, "", true, nil); err == nil {
		u.NumericRuleType = &numericRuleType
		u.Type = RuleTypeNumericRuleType
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Rule", string(data))
}

func (u Rule) MarshalJSON() ([]byte, error) {
	if u.RegexRuleType != nil {
		return utils.MarshalJSON(u.RegexRuleType, "", true)
	}

	if u.PatternRuleType != nil {
		return utils.MarshalJSON(u.PatternRuleType, "", true)
	}

	if u.NumericRuleType != nil {
		return utils.MarshalJSON(u.NumericRuleType, "", true)
	}

	return nil, errors.New("could not marshal union type Rule: all fields are null")
}

// ValidationRule - The Validation rule definition.
type ValidationRule struct {
	// Title of the validation rule.
	Title string `json:"title"`
	// Placeholder for the validation rule.
	Placeholder *string `json:"placeholder,omitempty"`
	Rule        *Rule   `json:"rule,omitempty"`
	// Schema version of the validation rule.
	SchemaVersion string `json:"_schema_version"`
	// Unique identifier for the validation rule.
	ID string `json:"_id"`
	// Organization ID that owns this rule.
	OrganizationID string `json:"_organization_id"`
	// ISO timestamp when the rule was created.
	CreatedAt string `json:"created_at"`
	// ISO timestamp when the rule was last updated.
	UpdatedAt string `json:"updated_at"`
	// User ID of the creator.
	CreatedBy string `json:"created_by"`
	// User ID of the last updater.
	UpdatedBy string `json:"updated_by"`
}

func (o *ValidationRule) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *ValidationRule) GetPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.Placeholder
}

func (o *ValidationRule) GetRule() *Rule {
	if o == nil {
		return nil
	}
	return o.Rule
}

func (o *ValidationRule) GetSchemaVersion() string {
	if o == nil {
		return ""
	}
	return o.SchemaVersion
}

func (o *ValidationRule) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ValidationRule) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *ValidationRule) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *ValidationRule) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *ValidationRule) GetCreatedBy() string {
	if o == nil {
		return ""
	}
	return o.CreatedBy
}

func (o *ValidationRule) GetUpdatedBy() string {
	if o == nil {
		return ""
	}
	return o.UpdatedBy
}
