// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-validation-rule/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
)

var _ provider.Provider = (*EpilotValidationRuleProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*EpilotValidationRuleProvider)(nil)

type EpilotValidationRuleProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// EpilotValidationRuleProviderModel describes the provider data model.
type EpilotValidationRuleProviderModel struct {
	EpilotAuth types.String `tfsdk:"epilot_auth"`
	ServerURL  types.String `tfsdk:"server_url"`
}

func (p *EpilotValidationRuleProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "epilot-validation-rule"
	resp.Version = p.version
}

func (p *EpilotValidationRuleProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"epilot_auth": schema.StringAttribute{
				MarkdownDescription: `Authorization header with epilot OAuth2 bearer token.`,
				Required:            true,
				Sensitive:           true,
			},
			"server_url": schema.StringAttribute{
				Description: `Server URL (defaults to https://validation-rules.sls.epilot.io)`,
				Optional:    true,
			},
		},
	}
}

func (p *EpilotValidationRuleProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data EpilotValidationRuleProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serverUrl := data.ServerURL.ValueString()

	if serverUrl == "" {
		serverUrl = "https://validation-rules.sls.epilot.io"
	}

	security := shared.Security{}

	if !data.EpilotAuth.IsUnknown() {
		security.EpilotAuth = data.EpilotAuth.ValueString()
	}

	if security.EpilotAuth == "" {
		resp.Diagnostics.AddError(
			"Missing Provider Security Configuration",
			"Provider configuration epilot_auth attribute must be configured.",
		)
	}

	providerHTTPTransportOpts := ProviderHTTPTransportOpts{
		SetHeaders: make(map[string]string),
		Transport:  http.DefaultTransport,
	}

	httpClient := http.DefaultClient
	httpClient.Transport = NewProviderHTTPTransport(providerHTTPTransportOpts)

	opts := []sdk.SDKOption{
		sdk.WithServerURL(serverUrl),
		sdk.WithSecurity(security),
		sdk.WithClient(httpClient),
	}

	client := sdk.New(opts...)
	resp.DataSourceData = client
	resp.EphemeralResourceData = client
	resp.ResourceData = client
}

func (p *EpilotValidationRuleProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewValidationRuleResource,
	}
}

func (p *EpilotValidationRuleProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewValidationRuleDataSource,
	}
}

func (p *EpilotValidationRuleProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &EpilotValidationRuleProvider{
			version: version,
		}
	}
}
