// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type All struct {
	RegexFactCondition   *RegexFactCondition   `queryParam:"inline" tfsdk:"regex_fact_condition" tfPlanOnly:"true"`
	RegexNestedCondition *RegexNestedCondition `queryParam:"inline" tfsdk:"regex_nested_condition" tfPlanOnly:"true"`
}
