// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type CreateValidationRuleRequestRule struct {
	NumericRuleType *NumericRuleType `queryParam:"inline" tfsdk:"numeric_rule_type" tfPlanOnly:"true"`
	PatternRuleType *PatternRuleType `queryParam:"inline" tfsdk:"pattern_rule_type" tfPlanOnly:"true"`
	RegexRuleType   *RegexRuleType   `queryParam:"inline" tfsdk:"regex_rule_type" tfPlanOnly:"true"`
}
