// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type NumericNestedCondition struct {
	One   *NumericNestedCondition1 `queryParam:"inline" tfsdk:"one" tfPlanOnly:"true"`
	Two   *NumericNestedCondition2 `queryParam:"inline" tfsdk:"two" tfPlanOnly:"true"`
	Three *NumericNestedCondition3 `queryParam:"inline" tfsdk:"three" tfPlanOnly:"true"`
}
