// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type NumericFactCondition struct {
	One   *NumericFactCondition1 `queryParam:"inline" tfsdk:"one"`
	Two   *NumericFactCondition2 `queryParam:"inline" tfsdk:"two"`
	Three *NumericFactCondition1 `queryParam:"inline" tfsdk:"three"`
	Four  *NumericFactCondition4 `queryParam:"inline" tfsdk:"four"`
}
