// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type NumericCondition struct {
	One   *NumericCondition1 `queryParam:"inline" tfsdk:"one"`
	Two   *NumericCondition2 `queryParam:"inline" tfsdk:"two"`
	Three *NumericCondition3 `queryParam:"inline" tfsdk:"three"`
}
