// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NumericFactConditionSchemasParams struct {
	AllowLeadingZeroes types.Bool   `tfsdk:"allow_leading_zeroes"`
	ErrorMessage       types.String `tfsdk:"error_message"`
}
