// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type NumericNestedCondition struct {
	One   *NumericNestedCondition1 `queryParam:"inline" tfsdk:"one"`
	Two   *NumericNestedCondition2 `queryParam:"inline" tfsdk:"two"`
	Three *NumericNestedCondition3 `queryParam:"inline" tfsdk:"three"`
}
