// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type NumericConditionAll struct {
	NumericFactCondition   *NumericFactCondition   `queryParam:"inline" tfsdk:"numeric_fact_condition"`
	NumericNestedCondition *NumericNestedCondition `queryParam:"inline" tfsdk:"numeric_nested_condition"`
}
