// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type NumericFactCondition struct {
	One   *NumericFactCondition1 `queryParam:"inline" tfsdk:"one" tfPlanOnly:"true"`
	Two   *NumericFactCondition2 `queryParam:"inline" tfsdk:"two" tfPlanOnly:"true"`
	Three *NumericFactCondition1 `queryParam:"inline" tfsdk:"three" tfPlanOnly:"true"`
	Four  *NumericFactCondition4 `queryParam:"inline" tfsdk:"four" tfPlanOnly:"true"`
}
