// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type NumericConditionAll struct {
	NumericFactCondition   *NumericFactCondition   `queryParam:"inline" tfsdk:"numeric_fact_condition" tfPlanOnly:"true"`
	NumericNestedCondition *NumericNestedCondition `queryParam:"inline" tfsdk:"numeric_nested_condition" tfPlanOnly:"true"`
}
