// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PatternFactCondition struct {
	One   *PatternFactCondition1 `queryParam:"inline" tfsdk:"one"`
	Two   *PatternFactCondition1 `queryParam:"inline" tfsdk:"two"`
	Three *PatternFactCondition3 `queryParam:"inline" tfsdk:"three"`
	Four  *Four                  `queryParam:"inline" tfsdk:"four"`
}
