// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PatternConditionAll struct {
	PatternFactCondition   *PatternFactCondition   `queryParam:"inline" tfsdk:"pattern_fact_condition" tfPlanOnly:"true"`
	PatternNestedCondition *PatternNestedCondition `queryParam:"inline" tfsdk:"pattern_nested_condition" tfPlanOnly:"true"`
}
