// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PatternFactCondition1 struct {
	Fact     types.String                `tfsdk:"fact"`
	Operator types.String                `tfsdk:"operator"`
	Params   *PatternFactConditionParams `tfsdk:"params"`
	Value    types.Float64               `tfsdk:"value"`
}
