// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PatternNestedCondition struct {
	One   *PatternNestedCondition1 `queryParam:"inline" tfsdk:"one"`
	Two   *PatternNestedCondition2 `queryParam:"inline" tfsdk:"two"`
	Three *PatternNestedCondition3 `queryParam:"inline" tfsdk:"three"`
}
