// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PatternFactConditionParams struct {
	End          types.Float64 `tfsdk:"end"`
	ErrorMessage types.String  `tfsdk:"error_message"`
	Start        types.Float64 `tfsdk:"start"`
}
