// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PatternCondition struct {
	One   *PatternCondition1 `queryParam:"inline" tfsdk:"one"`
	Two   *PatternCondition2 `queryParam:"inline" tfsdk:"two"`
	Three *PatternCondition3 `queryParam:"inline" tfsdk:"three"`
}
