// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type RegexNestedCondition struct {
	One   *One   `queryParam:"inline" tfsdk:"one" tfPlanOnly:"true"`
	Two   *Two   `queryParam:"inline" tfsdk:"two" tfPlanOnly:"true"`
	Three *Three `queryParam:"inline" tfsdk:"three" tfPlanOnly:"true"`
}
