// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type RegexCondition struct {
	One   *RegexCondition1 `queryParam:"inline" tfsdk:"one" tfPlanOnly:"true"`
	Two   *RegexCondition2 `queryParam:"inline" tfsdk:"two" tfPlanOnly:"true"`
	Three *RegexCondition3 `queryParam:"inline" tfsdk:"three" tfPlanOnly:"true"`
}
