// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type RegexRuleType struct {
	Conditions RegexCondition `tfsdk:"conditions"`
	Type       types.String   `tfsdk:"type"`
}
