// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type RegexCondition struct {
	One   *RegexCondition1 `queryParam:"inline" tfsdk:"one"`
	Two   *RegexCondition2 `queryParam:"inline" tfsdk:"two"`
	Three *RegexCondition3 `queryParam:"inline" tfsdk:"three"`
}
