// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UsedBy struct {
	SchemaSlug types.String `tfsdk:"schema_slug"`
	SourceID   types.String `tfsdk:"source_id"`
	Type       types.String `tfsdk:"type"`
}
